about/urls.py
from django.urls import path

from . import views

app_name = "author"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

# у нас два варианта: вывод всех постов или по сообществу
urlpatterns = [
    # долны быть выше, иначе их перехватит /<username>/
    path("404/", views.page_not_found, name="404"),
    path("500/", views.server_error, name="500"),
    path("", views.index, name="index"),
    path("<str:username>/<int:post_id>/comment/",
         views.add_comment,
         name="add_comment"),
    path("follow/", views.view_follow_index, name="follow_index"),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
    path("group/<slug:slug>/", views.group_posts, name="group_slug"),
    path("group/", views.show_groups, name="show_groups"),
    path("new/", views.new_post, name="new_post"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.view_post, name="post"),
    # проверить name для edit_post либо new_post
    path(
        "<str:username>/<int:post_id>/edit/",
        views.new_post,
        name="edit_post"
    ),
]

yatube/urls.py
# from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path("about/", include("about.urls", namespace="about")),
    # регистрация и авторизация
    path("auth/", include("users.urls")),
    # если не нашлось нужного шаблона для /auth
    path("auth/", include("django.contrib.auth.urls")),
    # импорт правил из приложения admin
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    """ описание поста """
    text = models.TextField(verbose_name="Текст",
                            help_text="Содержимое поста")

    pub_date = models.DateTimeField(verbose_name="Дата публикации",
                                    auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts",
                               verbose_name="Автор")
    # создаем связь поста с сообществом
    group = models.ForeignKey("Group", on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              related_name="posts",
                              verbose_name="Сообщество",
                              help_text="Название сообщества")

    image = models.ImageField(upload_to="posts/",
                              verbose_name="Картинка",
                              help_text="Картинка к посту",
                              blank=True, null=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    """ описание сообщества """
    title = models.CharField("Название сообщества", max_length=200)
    slug = models.SlugField("Адрес сообщества", max_length=100, unique=True,
                            help_text=("уникальное название сообщества "
                                       "латиницей для адресной строки"))

    description = models.TextField("Описание", max_length=100,
                                   default="",
                                   help_text="Описание сообщества")

    def __str__(self):
        """ Выводим поле title"""
        return self.title


class Comment(models.Model):
    """ Описание модели комментария """
    post = models.ForeignKey("Post", on_delete=models.CASCADE,
                             related_name="comments")

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="comment",
                               verbose_name="Автор комментария")

    text = models.TextField(verbose_name="Текст",
                            help_text="Содержимое поста")

    created = models.DateTimeField(verbose_name="Дата комментария",
                                   auto_now_add=True)


class Follow(models.Model):
    """ Модель для хранения подписок я - user подписываюсь на author """
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower")

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following")
    # TODO выдает ошибки
    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=["user", "author"],
    #                                 name="follow-constraint")
    #     ]

posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render)
from django.urls import reverse_lazy
from django.utils import timezone

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post


def follow_authors_context(request):
    """ передает список подписки на авторов для оформления кнопок """
    if not request.user.is_authenticated:
        return None
    links = Follow.objects.filter(user=request.user)
    authors = [link.author.id for link in links]
    return authors


@login_required
def view_follow_index(request):
    """ Вывод ленты подписок пользователя """
    # собираем все подписки пользователя
    authors = follow_authors_context(request)
    posts = Post.objects.prefetch_related("author").filter(author__in=authors)

    page, paginator = get_page(request, posts)
    context = {"page": page, "paginator": paginator, "follow_index": True,
               "username": request.user, "authors": authors}

    return render(request, "index.html", context)


@login_required
def profile_follow(request, username):
    """ подписывает текущего пользователя на автора """
    if username == request.user.username:
        # TODO заменить
        return redirect("posts:index")
    user = get_object_or_404(get_user_model(), username=request.user)
    author = get_object_or_404(get_user_model(), username=username)
    count = Follow.objects.filter(user=user, author=author).count()
    if not count:
        Follow.objects.create(user=user, author=author)
    # TODO: проверить, что редирект с нашего сайта
    redirect_link = request.GET.get("next")
    # вернем пользователя туда откуда пришёл
    if redirect_link:
        return redirect(redirect_link)
    else:
        return redirect("/")


@login_required
def profile_unfollow(request, username):
    """ отписывает текущего пользователя на автора """
    user = get_object_or_404(get_user_model(), username=request.user)
    author = get_object_or_404(get_user_model(), username=username)

    count = Follow.objects.filter(user=user, author=author).count()

    if count:
        Follow.objects.get(user=user, author=author).delete()

    redirect_link = request.GET.get("next")
    if redirect_link:
        return redirect(redirect_link)
    else:
        return redirect("/")


def get_page(request, object_list):
    """ Возвращает контекст page от paginator """
    loc_paginator = Paginator(object_list, 10)
    page_number = request.GET.get("page")
    return loc_paginator.get_page(page_number), loc_paginator


def get_profile_data_dict(username, add_context=None):
    """ Возвращает словарь с данными профиля и объектом пользователя """
    user = get_object_or_404(get_user_model(), username=username)
    context = {
        "username": user,
        "posts_count": Post.objects.filter(author=user).count(),
    }
    if add_context:
        context.update(add_context)
    return context


def index(request):
    """ Вывод последних 10 постов из базы """
    post_list = Post.objects.prefetch_related("author").all()
    page, paginator = get_page(request, post_list)
    context = {"page": page, "paginator": paginator}

    authors = follow_authors_context(request)
    context.update({"authors": authors})
    return render(request, "index.html", context)


def group_posts(request, slug=None):
    # Получаем объект из базы соответствующий slug
    group = get_object_or_404(Group, slug=slug)
    # Получаем все посты принадлежащие slug через related_name
    posts = group.posts.prefetch_related("author").all()
    page, paginator = get_page(request, posts)
    # передаем paginator в контекст чтобы пройти тест
    context = {"group": group, "page": page, "paginator": paginator,
               "authors": follow_authors_context(request)}

    return render(request, "group.html", context)


def show_groups(request):
    """ Показывает страницу со списком всех сообществ """
    groups = get_list_or_404(Group)
    return render(request, "show_groups.html", {"groups": groups})


def profile(request, username):
    """ Выводит профиль пользователя и его посты """
    # цепляем данные профиля
    context = get_profile_data_dict(username)
    posts = context["username"].posts.prefetch_related("author").all()
    page, paginator = get_page(request, posts)  # костыль paginator для тестов
    author = get_object_or_404(get_user_model(), username=username)
    # подписан ли текущий пользователь на того что в профиле
    following = 0  # на скольких подписан
    followers = 0  # сколько подписчиков
    following_this_author = False
    if request.user.is_authenticated:
        if Follow.objects.filter(user=request.user, author=author).exists():
            following_this_author = True
    user = context["username"]
    following = user.follower.count()
    followers = user.following.count()
    following_list = user.follower.all()  # на кого подписан
    # followers_list = Follow.objects.filter(author=user)  # кто его читает
    followers_list = user.following.all()  # кто его читает

    context.update({"page": page, "paginator": paginator,
                    "following": following, "followers": followers,
                    "following_this_author": following_this_author,
                    "following_list": following_list,
                    "followers_list": followers_list})

    # обязательно отдаем username, на случай если нет постов
    return render(request, "profile.html", context)


def view_post(request, username, post_id):
    """ Посмотреть пост под номером post_id """
    context = get_profile_data_dict(username)
    post = get_object_or_404(Post, id=post_id,
                             author__username=context["username"])
    comments = Comment.objects.filter(post=post_id)
    # Так не работает, потому что может не быть комментариев, тогда придет 404
    # comments = get_list_or_404(Comment, post=post_id)
    form = CommentForm()
    context.update({"post": post, "post_id": post_id,
                    "comments": comments, "form": form})
    return render(request, "post.html", context)


@login_required
def add_comment(request, username, post_id):
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = get_object_or_404(get_user_model(),
                                           username=request.user)
        comment.post = get_object_or_404(Post, id=post_id)
        comment.save()
    return redirect("posts:post", username, post_id)


@login_required
def new_post(request, username=None, post_id=None):
    """ Создать/редактировать новый пост """
    instance = None
    new_post = True  # поумолчанию - создать если ниже не сказано иное
    # не тот пользователь - уходим
    if request.user.username != username and post_id:
        return redirect("posts:post", username, post_id)

    if username and post_id:  # Если установлены - значит редактирование
        instance = get_object_or_404(Post,
                                     author__username=username,
                                     id=post_id)
        new_post = False

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=instance)

    if request.GET or not form.is_valid():
        return render(request, "new_post.html",
                      {"form": form,
                       "new_post": new_post,
                       "post": instance})  # тест просит, но для чего не ясно

    post = form.save(commit=False)
    post.pub_date = timezone.now()
    post.author = request.user
    post.save()
    # если дошли сюда и пользователь совпадает, значит вернемся к посту
    if request.user.username == username:
        return redirect("posts:post", username, post_id)

    return redirect(reverse_lazy("posts:index"))


def page_not_found(request, exception):
    # Переменная exception содержит отладочную информацию,
    # выводить её в шаблон пользователской страницы 404 мы не станем
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404)


def server_error(request):
    return render(request, "misc/500.html", status=500)

posts/templates/posts/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    <a id="top"></a>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <h3>{% block header %}{% endblock %}</h3>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

posts/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' username post_id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body text-center">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Отправить</button>
                <a href="javascript:history.back()" name="Назад" class="btn btn-light">Назад</a>
            </div>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                @{{ item.author.username }} 
            </a>
            <small class="text-muted">({{ item.created | date:"d.m.Y" }})</small>
        </h5>

        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %} 

posts/templates/posts/follow_button.html
<li class="list-group-item">
    {% if following_this_author %}
    <a class="btn btn-lg btn-light" 
            href="{% url 'posts:profile_unfollow' username %}?next={{ request.path }}#{{ post.id }}" role="button"> 
                Отписаться</a> 
    {% else %}
    <a class="btn btn-lg btn-primary" 
            href="{% url 'posts:profile_follow' username %}?next={{ request.path }}#{{ post.id }}" role="button">
                Подписаться</a>
    {% endif %}
</li>

posts/templates/posts/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">· <a href="{% url 'about:author' %}">Об авторе</a> · <a href="{% url 'about:tech' %}">О технологиях</a> ·</p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

posts/templates/posts/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container">
    <h3>#{{ group }}</h3>
    <p>
        {{ group.description }}
    </p>
     <!-- Вывод ленты записей -->
         {% for post in page %}
           <!-- Вот он, новый include! -->
             {% include "post_item.html" with post=post %}
         {% endfor %}
</div>

 <!-- Вывод паджинатора -->
 {% if page.has_other_pages %}
     {% include "paginator.html" with items=page paginator=paginator%}
 {% endif %}
{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %} 
{% block title %} Последние обновления {% endblock %}

{% block content %}
{% load cache %}
{% cache 20 index_page page %}
<div class="container">
  <h3> {% if not follow_index %} Последние обновления на сайте {% else %} Лента пользователя @{{ username }} {% endif %}</h3>
            <!-- Вывод ленты записей -->
                {% if page %}
                  {% for post in page %}
                    <!-- Вот он, новый include! -->
                      {% include "post_item.html" with post=post %}
                  {% endfor %}
                {% else %}
                  У вас нет подписок
                {% endif %}
                <!-- Вывод паджинатора -->
                {% if page.has_other_pages %}
                        {% include "paginator.html" with items=page paginator=paginator%}
                {% endif %}
              </div>
              {% endcache %}
{% endblock %} 

posts/templates/posts/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
        <li>
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:show_groups' %}">
                Сообщества
            </a>
        </li>
    </ul>
</div>
{% endif %}

posts/templates/posts/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    {% include 'menu.html' %}
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        <a href="{% url 'posts:profile' user.username %}"><span style="color:red"><b>{{ user.username.0|upper }}</span><span style="color:rgb(0, 0, 0)">{{ user.username|slice:"1:" }}</b></span></a>.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

posts/templates/posts/new_post.html
{% extends "base.html" %}

    {% block title %}
        {% if new_post is True %}
            Новая запись
        {% else %}
            Редактировать запись
        {% endif %}
        {% endblock %}
        
    {% block header %}
        {% if new_post is True %}
            Новая запись
        {% else %}
            Редактировать запись
        {% endif %}    
    {% endblock %}
    
    {% block content %}
    {% load user_filters %}
    
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <!-- <div class="card-header">Создать запись</div> -->
                <div class="card-body">
                    {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-8">
                                {{ field | addclass:"form-control"}}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        
                        <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                    {% if new_post is True %}Создать{% else %}Обновить{% endif %}    
                            </button>
                            <a href="javascript:history.back()" name="Назад" class="btn btn-light">Назад</a>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
    {% endblock %} 

posts/templates/posts/paginator.html
{% if page.has_other_pages %}
    <nav>
        <div class="text-center">
            <ul class="pagination justify-content-center">
                {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Предыдущая</span>
                </li>
                {% endif %}
                {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                <li class="page-item active">
                    <span class="page-link">{{ i }}
                        <span class="sr-only">(текущая)</span>
                    </span>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Следующая &raquo;</span>
                </li>
                {% endif %}
            </ul>
            <a class="btn btn-sm btn-light text-center" href="#top">&uarr; Наверх &uarr;</a>
        </div>
    </nav>
{% endif %}

posts/templates/posts/post_item.html
<div class="card mb-3 mt-1 shadow-sm">
    <!-- Отображение картинки -->
    <a id="{{ post.id }}"></a>
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <div class="btn-group">
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {# Если following не передан, значит кнопка подписаться не покажется (страница профиля) #}
        {% if user != post.author and following_this_author is None %}
            {% if not post.author.id in authors %}
            <a href="{% url 'posts:profile_follow' post.author.username %}?next={{ request.path }}#{{ post.id }}" role="button">[подписаться]</a>
            {% else %}
            <a href="{% url 'posts:profile_unfollow' post.author.username %}?next={{ request.path }}#{{ post.id }}" role="button">[отписаться]</a>
            {% endif %}
        {% endif %}
      </div>
      <br>
      {{ post.text|linebreaksbr }}
    </p>
    <div class="text-left">
      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'posts:group_slug' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
    </div>
  
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
              {% if user.is_authenticated %}
              <a class="btn btn-sm btn-light" href="{% url 'posts:post' post.author.username post.id %}" role="button">
                  Добавить комментарий
              </a>
              {% else %}
              <a class="btn btn-sm btn-light"href="{% url 'login' %}?next={% url 'posts:post' post.author.username post.id %}">Для комментариев вам нужно&nbsp;залогиниться</a>
              {% endif %}
              {% if post.comments.exists %}
              <button class="btn btn-sm btn-light" role="button" disabled>
                      Комментариев: {{ post.comments.count }}
              </button>
              {% endif %}
            
          </div>
          <!-- Ссылка на редактирование поста для автора -->
          <div class="btn-group">
            {% if user == post.author %}
            <a class="btn btn-sm btn-link" href="{% url 'posts:edit_post' post.author.username post.id %}" role="button">Редактировать</a>
            {% endif %}
            <!-- Дата публикации поста -->
            <button class="btn btn-sm" role="button" disabled>
              <small class="text-muted">{{ post.pub_date|date:"d.m.Y" }}</small>
            </button>
        
          </div>
      </div>
    </div>
  </div> 

posts/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Последние записи автора @{{ user.username }}{% endblock %}
{% block header %}Последние записи автора @{{ user.username }}{% endblock %}
{% block content %}
{% load thumbnail %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-3 mb-3 mt-1">
            <div class="card">
                <div class="card-body">
                    <div class="h2">
                        <!-- Имя автора -->
                        {{ username.get_full_name }}
                    </div>
                    <div class="h3 text-muted">
                        <!-- username автора -->
                        @{{ username }}
                    </div>
                </div>
                {% if username != user %}
                    <div class="text-center">{% include 'follow_button.html' %}</div>
                {% endif %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="h6 text-muted">
                            Подписчиков: {{ followers }} <br/>
                            Подписан: {{ following }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">
                            <!-- Количество записей -->
                            Записей: {{ posts_count }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">
                            <!-- Подписчики -->
                            Подписки:<br>
                            {% if following_list %}
                                {% for following_user in following_list %}
                                <a href="{% url 'posts:profile' following_user.author %}">@{{ following_user.author }}</a><br>
                                {% endfor %}
                            {% else %}
                                Нет подписок
                            {% endif %}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">
                            <!-- Подписчики -->
                            Подписчики:<br>
                            {% if followers_list %}
                                {% for follower_user in followers_list %}
                                <a href="{% url 'posts:profile' follower_user.user %}">@{{ follower_user.user }}</a><br>
                                {% endfor %}
                            {% else %}
                                нет подписчиков
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-9">
            {% for post in page %}
                {% include 'post_item.html' %}
            {% endfor %}
            {% include 'paginator.html' %}
            <!-- Конец блока с отдельным постом -->

            <!-- Остальные посты -->

            <!-- Здесь постраничная навигация паджинатора -->
        </div>
    </div>
</main>

{% endblock %}

posts/templates/posts/show_groups.html
{% extends "base.html" %}
{% block title %}Сообщества{% endblock %}
{% block header %}Сообщества{% endblock %}
{% block content %}

<div class="list-group">
    {% for group in groups %}
        <a class="list-group-item list-group-item-action" href="{{ group.slug }}">{{ group.title }}</a>
        {% endfor %}
        <a class="list-group-item list-group-item-action" href="{% url 'posts:index' %}">Посмотртеть всё</a>
</div>
{% endblock %} 